<a href="https://colab.research.google.com/github/ChennamaReddyRevanth/Python_for_DataScience/blob/main/practicing_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Normal Numpy operations


In [ ]:
import numpy as np

In [ ]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [ ]:
print("x    :",x)
print("x+5  :",x+5)
print("x-2  :", x-2)
print("x*3  :",x*3)
print("x/2  :",x/2)
print("x//2 :",x//2)

x    : [1 2 3 4 5]
x+5  : [ 6  7  8  9 10]
x-2  : [-1  0  1  2  3]
x*3  : [ 3  6  9 12 15]
x/2  : [0.5 1.  1.5 2.  2.5]
x//2 : [0 1 1 2 2]


##Array Arithmetic using uninary unversial functions

In [ ]:
print("x+3  :",np.add(x,3))
print("x+1  :",np.subtract(x,1))
print("x*3  :",np.multiply(x,3))
print("x/2  :",np.divide(x,2))
print("x//2 :",np.floor_divide(x,2))
print("exponent :",np.exp(x))
print("x**2 :",np.power(x,2))
print("X%3  :",np.mod(x,3))

x+3  : [4 5 6 7 8]
x+1  : [0 1 2 3 4]
x*3  : [ 3  6  9 12 15]
x/2  : [0.5 1.  1.5 2.  2.5]
x//2 : [0 1 1 2 2]
exponent : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
x**2 : [ 1  4  9 16 25]
X%3  : [1 2 0 1 2]


Array Arithmetic ucing Binary unversial functions


In [ ]:
y=np.arange(6,11)
print("x+y  :",np.add(x,y))
print("x+1  :",np.subtract(x,y))
print("x*3  :",np.multiply(x,y))
print("x/2  :",np.divide(x,y))
print("x//2 :",np.floor_divide(x,y))
print("exponent :",np.exp(x))
print("x**2 :",np.power(x,2))
print("X%3  :",np.mod(x,y))


x+y  : [ 7  9 11 13 15]
x+1  : [-5 -5 -5 -5 -5]
x*3  : [ 6 14 24 36 50]
x/2  : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
x//2 : [0 0 0 0 0]
exponent : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
x**2 : [ 1  4  9 16 25]
X%3  : [1 2 3 4 5]


#Absolute values

In [ ]:
b=np.arange(-4,5)
abs(b)

array([4, 3, 2, 1, 0, 1, 2, 3, 4])

# This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [ ]:
c=np.array([3-4j,4-3j,2+0j,0+2j])
abs(c)

array([5., 5., 2., 2.])

#Trigonometric functions
NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions. We'll start by defining an array of angles:

In [ ]:
rr=np.linspace(0,5,4)
print("sin(rr)   :",np.sin(rr))
print("cos(rr)   :",np.cos(rr))
print("tan(rr)   :",np.tan(rr))


sin(rr)   : [ 0.          0.99540796 -0.19056796 -0.95892427]
cos(rr)   : [ 1.         -0.09572355 -0.981674    0.28366219]
tan(rr)   : [  0.         -10.39877834   0.19412551  -3.38051501]


The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero. Inverse trigonometric functions are also available:

In [ ]:
x=[-1,0,1]
print("arcsin(rr)   :",np.arcsin(x))
print("arccos(rr)   :",np.arccos(x))
print("arctan(rr)   :",np.arctan(x))


arcsin(rr)   : [-1.57079633  0.          1.57079633]
arccos(rr)   : [3.14159265 1.57079633 0.        ]
arctan(rr)   : [-0.78539816  0.          0.78539816]


# Exponents and logarithms

In [ ]:
x=[5,4,6,3,2,7]
print("x    :",x)
print("e^x  :",np.exp(x))
print("2^x  :",np.exp2(x))
print("3^x  :",np.power(3,x))

x    : [5, 4, 6, 3, 2, 7]
e^x  : [ 148.4131591    54.59815003  403.42879349   20.08553692    7.3890561
 1096.63315843]
2^x  : [ 32.  16.  64.   8.   4. 128.]
3^x  : [ 243   81  729   27    9 2187]


The inverse of the exponentials, the logarithms, are also available. The basic np.log gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:



In [ ]:
x=[1,2,4,7,10]
print("ln(x)   :",np.log(x))
print("log2(x) :",np.log2(x))
print("log10(x):",np.log10(x))


ln(x)   : [0.         0.69314718 1.38629436 1.94591015 2.30258509]
log2(x) : [0.         1.         2.         2.80735492 3.32192809]
log10(x): [0.         0.30103    0.60205999 0.84509804 1.        ]


#aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling reduce on the add ufunc returns the sum of all elements in the array:

In [ ]:
x = np.arange(1, 6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

print(np.add.accumulate(x))

print(np.multiply.accumulate(x))

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


# How to create your own UFUNC

In [ ]:
import numpy as np
def subtract(x,y,z):
  return (x-y-z)
subtract=np.frompyfunc(subtract,3,1)
print(subtract([8,7,9],[5,3,4],[1,2,3]))

[2 2 2]


In [ ]:
x=[[1,2,3],[5,6,7]]
print("adding all elements in an array ",np.sum(x))
x=[2,3,4]
y=[6,7,8]
print("adding all elements in different array",np.sum([x,y])

30